---
title: "aoc2022 - 01"
author: "Stefan Haussner"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(adventdrob)

options(scipen = 999)
```

```{r}
input <- read_file("input/01.txt")

elf_calories <- input %>% 
  str_replace_all(pattern = "\n\n", replacement = ";") %>% 
  str_replace_all(pattern = "\n", replacement = "\t") %>% 
  str_replace_all(pattern = ";", replacement = "\n") %>% 
  read_csv(col_names = FALSE) %>% 
  mutate(elf = 1:n()) %>% 
  separate_rows(X1, sep = "\t") %>% 
  mutate(calories = as.numeric(X1)) %>% 
  group_by(elf) %>% 
  summarise(calories = sum(calories)) %>% 
  arrange(desc(calories))

elf_calories %>% slice_head(n=1)
```

```{r}
input <- read_file("input/01.txt")

input %>% 
  str_replace_all(pattern = "\n\n", replacement = ";") %>% 
  str_replace_all(pattern = "\n", replacement = "\t") %>% 
  str_replace_all(pattern = ";", replacement = "\n") %>% 
  read_csv(col_names = FALSE) %>% 
  mutate(elf = 1:n()) %>% 
  separate_rows(X1, sep = "\t") %>% 
  mutate(calories = as.numeric(X1)) %>% 
  group_by(elf) %>% 
  summarise(calories = sum(calories)) %>% 
  arrange(desc(calories)) %>% 
  mutate(group = 1:n(),
         group = case_when(group %in% 1:3 ~ 1,
                           TRUE ~ 0)) %>% 
  filter(group == 1) %>% 
  summarise(calories = sum(calories))
```

